version: '3.8'

services:
  db:
    image: postgres:16
    container_name: my-postgres
    environment:
      POSTGRES_DB: SpringWeb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - springwebmvc_gdata:/var/lib/postgresql/data

  redis:
    image: redis:7.4.2
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: 7BjCipIKjOP9HA1goG200W/Z74UK+5+

volumes:
  springwebmvc_gdata:
